version: '3.3'

services:
 db:
  image: mysql:5.6
  volumes:
       - db_data:/var/lib/mysql
  ports: 
       - "3360:3306"
  restart: always
  environment:
      -MYSQL_ROOT_PASSWORD: admin

 phpmyadmin:
  depends_on:
       - db
  image: phpmyadmin/phpmyadmin
  ports:
       - "8001:80"
  restart: always
  environment:
      -MYSQL_ROOT_PASSWORD: admin


volumes:
    db_data: {} 
